### ISSUE TITLE
[BUG]: Potentially caused a file to go missing

### ISSUE THREAD

**Issue by cwriasir** [Falcion/UNITADE.md#16]
### What the essence of the bug

**I failed to replicate what had just happened, thus the "potentially", but I thought it would be somewhat informative to create this issue in case there really is some bug that might cause similar problems in the future.**

This extension has brought convenience to my in-vault management so far, so thanks for that. With all due respect, though, the plugin (or the toggling off thereof) _potentially_ caused a file to go missing.

Context: I accidentally opened an SQLite database file (`*.db`) in my vault while this plugin was enabled. Intending to reopen it with some other external application, I opened another existing Markdown file in the same directory in the same tab, and toggled off this plugin in the Community Plugins page. When I came back to the side panel, the `*.db` file vanished from the side panel—it turned out that the file had gone missing from the file system.

Environment:
- **OS**: `Android 11 (API level 30)`
- **Obsidian**: `1.4.9 (108)`
- **Plugins enabled (managed by Obsidian plugin `plugin-manager`)**: `buttons,calendar,cm-chs-patch,cmdr,darlal-switcher-plus,dataview,duplicate-line,note-refactor-obsidian,obsidian-admonition,obsidian-heading-shifter,obsidian-image-toolkit,obsidian-kanban,obsidian-link-embed,obsidian-list-callouts,obsidian-metatable,obsidian-org-mode,obsidian-outliner,obsidian-paste-to-current-indentation,obsidian-style-settings,obsidian-tasks-plugin,obsidian-zoom,plugin-manager,quickadd,remember-cursor-position,table-editor-obsidian,tag-wrangler,templater-obsidian,unitade,`
- It was highly unlikely that any application other than Obsidian was manipulating the database file at the time, so everything most definitely happened in Obsidian.

### Version of an project's essence

...

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Considering the fact that UNITADE does not work with the file system (except reading plugins folder from vault), but only with their registration and does this through the Obsidian's API, it is unlikely that the problem lies specifically in this plugin, however, thanks for this issue, in case the bug is repeated, this issue will be mentioned there too.

And again, thanks for the issue!

**Comment by Falcion** [comment]
Remembering this topic, as it turned out, the combination of this plugin and the OBSIDIAN functionality itself can, at a minimum, damage files; in the latest update (2.0.0), two modes for dynamically registering extensions were added, and a module for ignoring extensions/files was also added.

To my regret, it is still unknown how to specifically avoid such situations, except to be more careful in using the plugin (which was also implemented in the latest update), because the whole point of editing files lies only and only in the application, and not in the plugin.
