### ISSUE TITLE
[FEATURE]: Support for different editors/syntaxes

### ISSUE THREAD

**Issue by Servinjesus1** [Falcion/UNITADE.md#4]
### Contact details

@Servinjesus1

### What the essence of your feature request

It would be awesome if certain extensions could be customized to open in different editor schemas in Obsidian. For example, @deathau created a plugin to [view INI files in Obsidian](https://github.com/deathau/ini-obsidian) which essentially registers the extension with an ini syntax highlight scheme for CodeMirror's viewer. He uses the same kind of code to syntax highlight code blocks in normal markdown files, but adapted it to open `ini` files in this case.

If this extension could extend this notion to cover many different syntaxes in CodeMirror, that would be an excellent first step. I am not sure if other schemas besides CodeMirror and Obsidian's markdown editor make sense, but in general I could see users being able to populate a table of extension, schema, and syntax where each file type could be assigned an editor and a syntax to control highlighting.

The work required for this might be a little nontrivial, though, as currently the plugin doesn't seem to support dynamic registration reloading or catching errors associated with already registered extensions (c.f. other requests)

### On what OS you want to maintain your request.

Windows, macOS

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Interim report: so far there was an attempt to implement a syntax highlight like in [cm-editor-syntax-highlight-obsidian by deathau](https://github.com/deathau/cm-editor-syntax-highlight-obsidian) with some adaptive changes (because it was created only for codeblocks), but there was no practical results not only by code but by styling too (because there is no universal standards for writing SCSS styling guide), maybe there is some solution for this case, but I can't come with it.

So, next try was syntax highlighting represented by the same system which was in the [ini-obsidian](https://github.com/deathau/ini-obsidian) where there is custom view with CM and custom SCSS for data type, but, it is not working, not in my plugin, not in the original (I compiled the archived version and it does nothing except opening file, I think it's related to Obsidian API).

Also, about your request for custom editors, this thing is mostly beyond my authority, in future (or already in dev) version of plugin you can only force-opening in the OBSIDIAN, but other will be opened by default editors, some files like .EXE would be open by themselves, system defines them with help of user, meaning you.

P.S: added dynamic registry of extensions, unfortunately, I can't see what extensions have already been registered, so it can cause some exceptions, but you can turn it off in the settings and it ignores critical files like .MD or folders which can cause "self-destory" of the plugin.

Most of changes see on the latest version, thanks for the issue.

**Comment by Falcion** [comment]
The topic of syntax highlighting is relevant again, more details in the last issue: #73

**Comment by Falcion** [comment]
Read more about new release related to this issue:
https://github.com/Falcion/UNITADE.md/releases/tag/v3.0.0
https://github.com/Falcion/UNITADE.md/blob/main/data/release/v3.0.0.md
