### ISSUE TITLE
[BUG]: Attempting to register an existing view type ""

### ISSUE THREAD

**Issue by Crabtronic** [Falcion/UNITADE.md#40]
### What the essence of the bug

On a fresh new vault, as soon as I enable Unitade without modifying anything I get : 

> VM208 plugin:unitade:930 Error: Attempting to register an existing view type ""
>     at t.registerView (app.js:1:1986259)
>     at t.registerView (app.js:1:2237447)
>     at _UNITADE_PLUGIN.__apply (VM208 plugin:unitade:924:14)
>     at _UNITADE_PLUGIN.eval (VM208 plugin:unitade:905:12)
>     at Generator.next (<anonymous>)
>     at fulfilled (VM208 plugin:unitade:60:24)

When I disable all community plugins the error change :

> VM217 plugin:unitade:885 Error: Attempting to register an existing file extension ".md"
>     at t.registerExtensions (app.js:1:1986648)
>     at t.registerExtensions (app.js:1:2237808)
>     at _UNITADE_PLUGIN.eval (VM217 plugin:unitade:883:14)
>     at Generator.next (<anonymous>)
>     at eval (VM217 plugin:unitade:73:61)
>     at new Promise (<anonymous>)
>     at __async (VM217 plugin:unitade:57:10)
>     at _UNITADE_PLUGIN.onunload (VM217 plugin:unitade:879:12)
>     at e.unload (app.js:1:1167525)
>     at e.<anonymous> (app.js:1:2244246)

Do have I an issue with my obsidian installation ?

Thanks for this plugin and thanks in advance for helping.

### Version of an project's essence

2.1.1

### On what OS you have encountered the bug.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
I don't know what kind of anomaly happened, but this issue hasn't existed since april and "opened" only in this month.

In the latest version, these problems were solved in two ways: wiki specifies how the input mode works and where this error comes from, as well as about the error mode itself, I recommend reading.

https://github.com/Falcion/UNITADE.md/issues/70

And the wiki article:
- ["Silencing error" option](https://github.com/Falcion/UNITADE.md/wiki/Silencing-errors)

> [!Note]
> I'll close this issue, still don't understand how it could slipped through time and space and only show in the repository at the end of the year.
