### ISSUE TITLE
[BUG]: 50 mb exe in repo?

### ISSUE THREAD

**Issue by d9k** [Falcion/UNITADE.md#66]
### What the essence of the bug

[kubectl.exe](https://github.com/Falcion/UNITADE.md/blob/main/kubectl.exe)

### Version of an project's essence

2.2.1

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
This is .EXE file for Kubernetes inherited from project-template: [Patternugit](https://github.com/Falcion/Patternugit) and IS NOT included in any form of code or work of the plugin.

More about it for information at Kubernetes page (since project major maintenance is provided on/for Windows 10/11):
https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/
