### ISSUE TITLE
[BUG]: Obsidian Switcher++ doesn't see *.txt files

### ISSUE THREAD

**Issue by d9k** [Falcion/UNITADE.md#67]
### What the essence of the bug

[Obsidian Switcher++](https://github.com/darlal/obsidian-switcher-plus) doesn't see *.txt files. It worked with [deathau/txt-as-md-obsidian](https://github.com/deathau/txt-as-md-obsidian) plugin before Obsidian upgrade (1.3.5 -> 1.6.3) perfectly

If I rename one of *.txt files to *.md Obsidian Switcher sees it immediately

How to change UNITADE config to make Obsidian Switcher++ search in .txt files as in .md?

```json
{
  "markdown_overcharge": false,
  "extensions": "",
  "is_onload": false,
  "is_onload_unsafe": false,
  "forced_extensions": "",
  "is_ignore": false,
  "ignore_extensions": "",
  "ignore_masks": "",
  "is_grouped": true,
  "grouped_extensions": "md: txt;",
  "mobile_settings": {
    "enable": false,
    "extensions": "txt",
    "stable": true
  },
  "stable": true,
  "errors": {},
  "debug_mode": false
}
```

Tried `"extensions": "txt;"`, didn't help!

### Version of an project's essence

2.2.1

### On what OS you have encountered the bug.

Linux

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
The problem relates more to either the plugin itself or the OBSIDIAN application, since the plugin UNITADE does exactly the same thing when setting up as the plugin [txt-as-md-obsidian](https://github.com/deathau/txt-as-md-obsidian), explanation below.

When you configure the UNITADE plugin config as `"extensions": "txt;"` it does the same logic (without any additional bells and whistles) as the plugin:

https://github.com/deathau/txt-as-md-obsidian/blob/20c455e8aa1555a3c3d23fee935653a9563c7ef8/src/main.ts#L9

```javascript
    this.registerExtensions(["txt"], "markdown");
```

I'm not familiar with the Obsidian Switcher++ plugin, so it's possible that some of its updates (if you downloaded them) may have changed interactions with conditional .TXT files; otherwise, all that remains is to blame the original application itself and ask for support from the developers of the final plugin.

Thanks for the issue!

**Comment by d9k** [comment]
Turns out Obsidian Switcher++ sees *.txt files if I enable **core** Quick Switcher plugin. Closing the issue.
