### ISSUE TITLE
[QUESTION]: Error notification occurs when I zoom in and out the txt page. 

### ISSUE THREAD

**Issue by CanxinTang** [Falcion/UNITADE.md#80]
### What the essence of your question

![not understand](https://github.com/user-attachments/assets/308e95ce-20c8-4059-ae52-7f20dfb68387)

Look at the above img for detail, as I don't understand what is happening. 

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
**This error appears because when you zoom in or out on the code, the plugin interprets this as "increase" or "decrease" the font of the code editor.**


```typescript
    private __mousewheelHandler = async (event: WheelEvent) => {
        if (event.ctrlKey) {
            const delta = event.deltaY > 0 ? 1 : -1;


            const next = {
                ...this.plugin.settings,
                code_editor_settings: {
                    ...this.plugin.settings.code_editor_settings,
                    font_size: this.plugin.settings.code_editor_settings.font_size += delta,
                },
            }


            await this.plugin.uptSettings(next);
            
            this.monacoEditor!.updateOptions({
                fontSize: this.plugin.settings.code_editor_settings.font_size,
            });


            event.stopPropagation();
        }
    }
```

- https://github.com/Falcion/UNITADE.md/blob/5011e8f4142fa225d4f854ab2223cb389985595c/source/components/views/view_monaco.ts#L131C5-L151C6

Use the "silencing errors" mode in the additional functionality block of the plugin settings, more information about this mode:
https://github.com/Falcion/UNITADE.md/wiki/Silencing-errors

If this doesn't help, reopen this issue and I will be glad to help you!
