### ISSUE TITLE
[BUG]: window11  don

### ISSUE THREAD

**Issue by oliver6653** [Falcion/UNITADE.md#84]
### What the essence of the bug
On a fresh new vault, as soon as I enable Unitade without modifying anything I get :

![image](https://github.com/user-attachments/assets/60cd3f6f-27f9-4a0f-8e60-d5af984313c9)

![{DC9F7453-9519-483A-88E9-AF7ED00CEF83}](https://github.com/user-attachments/assets/555bd661-95c9-49cf-8c0b-e37cdf9b6896)

![image](https://github.com/user-attachments/assets/5cefefd6-2864-4f97-a956-2f3e9788f295)
![image](https://github.com/user-attachments/assets/82dd21d3-10ce-4a66-9f16-f0ff6d104d43)

besides , I can't understand how to solve the problem by [https://github.com/Falcion/UNITADE.md/issues/40]

best wishes,may help me, thanks!
### Version of an project's essence

3.0.2

### On what OS you have encountered the bug.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Hello, thanks for reopening the issue!

About your error, it can be fixed by "silencing errors" option in the settings of the plugin, try to find it, it still would show errors in settings list ("Errors" block of settings page), but silence (hide) any notifications and annoying messages which appear on your machine.

Recommended to read this wiki article of plugin:
["Silencing errors" in UNITADE](https://github.com/Falcion/UNITADE.md/wiki/Silencing-errors)

And use as reference issue #70, in which this error described and reason why it occurs and it is spammed in OBSIDIAN.

> [!Note]
> If issue persists, reopen the issue and write, if you could, more advanced case of your situation. Glad to help!
